/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.Readerdao;
import dao.Staffdao;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Reader;
import model.Staff;

/**
 *
 * @author Uygi
 */
public class pnreader extends javax.swing.JPanel {

    /**
     * Creates new form pnreader
     */
    private Staff s;
    private int ss;
    public pnreader(Staff s) {
        initComponents();
        showAllReader();
        pickAReader();
        this.s = s;
    }

    public void showAllReader() {
        Readerdao rdao = new Readerdao();
        lstr = rdao.getAllReader();
        DefaultTableModel dtm = (DefaultTableModel) tblreader.getModel();
        dtm.setRowCount(0);
        for (Reader r : lstr) {
            Vector vt = new Vector();
            vt.add(r.getId());
            vt.add(r.getName());
            vt.add(r.getPhone());

            dtm.addRow(vt);
        }
    }

    public void pickAReader() {
        tblreader.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int rowSelected = tblreader.getSelectedRow();
                int row = (int) tblreader.getValueAt(rowSelected, 0);

                Readerdao rdao = new Readerdao();
                Reader r = new Reader();
                r = rdao.getAReaderById(row);
                txtid.setText(Integer.toString((int) r.getId()));

                setPicture(lblimage, r.getAvatar());
                imgpath = r.getAvatar();

                txtname.setText(r.getName());
                txtphone.setText(r.getPhone());

                txtbirthday.setDate(r.getBirthday());
                if (r.getGender() == 1) {
                    rabmale.setSelected(true);
                    rabfemale.setSelected(false);
                } else {
                    rabmale.setSelected(false);
                    rabfemale.setSelected(true);
                }

                txtstatus.setText(Integer.toString(r.getStatus()));
                txtaddress.setText(r.getAddress());
                
                Staff st = new Staff();
                Staffdao stdao = new Staffdao();
                st = stdao.getAStaffById(r.getCrearedu());
                txtcreatedu.setText(st.getName());
                st = stdao.getAStaffById(r.getUpdatedu());
                txtupdatedu.setText(st.getName());
                
                ss = r.getCrearedu();
                txtcreatedd.setText(r.getCreatedd().toString());
                txtupdatedd.setText(r.getUpdatedd().toString());
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }
            @Override
            public void mouseReleased(MouseEvent e) {
            }
            @Override
            public void mouseEntered(MouseEvent e) {
            }
            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
    }

    public void setPicture(JLabel label, String filename) {
        try {
            image = ImageIO.read(new File(filename));
            ImageIcon icon = new ImageIcon(image.getScaledInstance(label.getWidth(), label.getHeight(), BufferedImage.SCALE_SMOOTH));
            label.setIcon(icon);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Something wrong with image");
            try {
                image = ImageIO.read(new File("C:\\Users\\Uygi\\Documents\\NetBeansProjects\\JavaProjectAT\\src\\img\\h.jpg"));
                ImageIcon icon = new ImageIcon(image.getScaledInstance(label.getWidth(), label.getHeight(), BufferedImage.SCALE_SMOOTH));
                lblimage.setIcon(icon);
            } catch (IOException exx) {
                System.out.println(exx);
            }
        }
    }

    public java.sql.Date convertJavaDateToSqlDate(java.util.Date date) {
        return new java.sql.Date(date.getTime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rabgender = new javax.swing.ButtonGroup();
        pnreader = new javax.swing.JPanel();
        pnleft = new javax.swing.JPanel();
        pnimage = new javax.swing.JPanel();
        lblimage = new javax.swing.JLabel();
        btnimage = new javax.swing.JButton();
        pnid = new javax.swing.JPanel();
        lblid = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        pnname = new javax.swing.JPanel();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        pnphone = new javax.swing.JPanel();
        lblphone = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        pnstatus = new javax.swing.JPanel();
        lblidentity = new javax.swing.JLabel();
        txtstatus = new javax.swing.JTextField();
        pnaddress = new javax.swing.JPanel();
        lbladdress = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        pnbirthday = new javax.swing.JPanel();
        lblbirthday = new javax.swing.JLabel();
        txtbirthday = new com.toedter.calendar.JDateChooser();
        pngender = new javax.swing.JPanel();
        lblgender = new javax.swing.JLabel();
        rabmale = new javax.swing.JRadioButton();
        rabfemale = new javax.swing.JRadioButton();
        pnupdatedu = new javax.swing.JPanel();
        lblupdatedu = new javax.swing.JLabel();
        txtupdatedu = new javax.swing.JTextField();
        pncreatedu = new javax.swing.JPanel();
        lblupdateduser1 = new javax.swing.JLabel();
        txtcreatedu = new javax.swing.JTextField();
        pnupdatedd = new javax.swing.JPanel();
        lblupdatedd = new javax.swing.JLabel();
        txtupdatedd = new javax.swing.JTextField();
        pncreatedd = new javax.swing.JPanel();
        lblcreatedd = new javax.swing.JLabel();
        txtcreatedd = new javax.swing.JTextField();
        pnright = new javax.swing.JPanel();
        pntbl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblreader = new javax.swing.JTable();
        pnbutton = new javax.swing.JPanel();
        pnsearchid = new javax.swing.JPanel();
        lblsearchid = new javax.swing.JLabel();
        txtsearchid = new javax.swing.JTextField();
        pnsearchname = new javax.swing.JPanel();
        lblsearchname = new javax.swing.JLabel();
        txtsearchname = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(767, 544));

        pnreader.setBackground(new java.awt.Color(51, 51, 51));
        pnreader.setPreferredSize(new java.awt.Dimension(767, 544));

        pnleft.setBackground(new java.awt.Color(51, 51, 51));
        pnleft.setPreferredSize(new java.awt.Dimension(523, 380));

        pnimage.setBackground(new java.awt.Color(51, 51, 51));
        pnimage.setPreferredSize(new java.awt.Dimension(250, 250));

        lblimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/h.jpg"))); // NOI18N

        btnimage.setBackground(new java.awt.Color(51, 51, 51));
        btnimage.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnimage.setForeground(new java.awt.Color(255, 102, 0));
        btnimage.setText("Pick Image");
        btnimage.setBorder(null);
        btnimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnimageLayout = new javax.swing.GroupLayout(pnimage);
        pnimage.setLayout(pnimageLayout);
        pnimageLayout.setHorizontalGroup(
            pnimageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(pnimageLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btnimage, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnimageLayout.setVerticalGroup(
            pnimageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnimageLayout.createSequentialGroup()
                .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnimage, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnid.setBackground(new java.awt.Color(51, 51, 51));

        lblid.setBackground(new java.awt.Color(0, 0, 0));
        lblid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblid.setForeground(new java.awt.Color(255, 102, 0));
        lblid.setText("ID:");

        txtid.setBackground(new java.awt.Color(51, 51, 51));
        txtid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtid.setForeground(new java.awt.Color(255, 255, 255));
        txtid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        javax.swing.GroupLayout pnidLayout = new javax.swing.GroupLayout(pnid);
        pnid.setLayout(pnidLayout);
        pnidLayout.setHorizontalGroup(
            pnidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnidLayout.createSequentialGroup()
                .addComponent(lblid, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 87, Short.MAX_VALUE))
            .addComponent(txtid)
        );
        pnidLayout.setVerticalGroup(
            pnidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnidLayout.createSequentialGroup()
                .addComponent(lblid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnname.setBackground(new java.awt.Color(51, 51, 51));

        lblname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 102, 0));
        lblname.setText("Name:");
        lblname.setPreferredSize(new java.awt.Dimension(36, 17));

        txtname.setBackground(new java.awt.Color(51, 51, 51));
        txtname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtname.setForeground(new java.awt.Color(255, 255, 255));
        txtname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        javax.swing.GroupLayout pnnameLayout = new javax.swing.GroupLayout(pnname);
        pnname.setLayout(pnnameLayout);
        pnnameLayout.setHorizontalGroup(
            pnnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtname)
            .addGroup(pnnameLayout.createSequentialGroup()
                .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnnameLayout.setVerticalGroup(
            pnnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnnameLayout.createSequentialGroup()
                .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnphone.setBackground(new java.awt.Color(51, 51, 51));
        pnphone.setPreferredSize(new java.awt.Dimension(75, 46));

        lblphone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblphone.setForeground(new java.awt.Color(255, 102, 0));
        lblphone.setText("Phone:");
        lblphone.setPreferredSize(new java.awt.Dimension(46, 17));

        txtphone.setBackground(new java.awt.Color(51, 51, 51));
        txtphone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtphone.setForeground(new java.awt.Color(255, 255, 255));
        txtphone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        javax.swing.GroupLayout pnphoneLayout = new javax.swing.GroupLayout(pnphone);
        pnphone.setLayout(pnphoneLayout);
        pnphoneLayout.setHorizontalGroup(
            pnphoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnphoneLayout.createSequentialGroup()
                .addComponent(lblphone, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(txtphone)
        );
        pnphoneLayout.setVerticalGroup(
            pnphoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnphoneLayout.createSequentialGroup()
                .addComponent(lblphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnstatus.setBackground(new java.awt.Color(51, 51, 51));
        pnstatus.setPreferredSize(new java.awt.Dimension(75, 46));

        lblidentity.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblidentity.setForeground(new java.awt.Color(255, 102, 0));
        lblidentity.setText("Status:");
        lblidentity.setPreferredSize(new java.awt.Dimension(46, 17));

        txtstatus.setBackground(new java.awt.Color(51, 51, 51));
        txtstatus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtstatus.setForeground(new java.awt.Color(255, 255, 255));
        txtstatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        javax.swing.GroupLayout pnstatusLayout = new javax.swing.GroupLayout(pnstatus);
        pnstatus.setLayout(pnstatusLayout);
        pnstatusLayout.setHorizontalGroup(
            pnstatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnstatusLayout.createSequentialGroup()
                .addComponent(lblidentity, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(txtstatus)
        );
        pnstatusLayout.setVerticalGroup(
            pnstatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnstatusLayout.createSequentialGroup()
                .addComponent(lblidentity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnaddress.setBackground(new java.awt.Color(51, 51, 51));

        lbladdress.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbladdress.setForeground(new java.awt.Color(255, 102, 0));
        lbladdress.setText("Address:");
        lbladdress.setPreferredSize(new java.awt.Dimension(46, 17));

        txtaddress.setBackground(new java.awt.Color(51, 51, 51));
        txtaddress.setColumns(20);
        txtaddress.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtaddress.setForeground(new java.awt.Color(255, 255, 255));
        txtaddress.setRows(5);
        txtaddress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jScrollPane2.setViewportView(txtaddress);

        javax.swing.GroupLayout pnaddressLayout = new javax.swing.GroupLayout(pnaddress);
        pnaddress.setLayout(pnaddressLayout);
        pnaddressLayout.setHorizontalGroup(
            pnaddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnaddressLayout.createSequentialGroup()
                .addComponent(lbladdress, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
        );
        pnaddressLayout.setVerticalGroup(
            pnaddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnaddressLayout.createSequentialGroup()
                .addComponent(lbladdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pnbirthday.setBackground(new java.awt.Color(51, 51, 51));
        pnbirthday.setPreferredSize(new java.awt.Dimension(75, 46));

        lblbirthday.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblbirthday.setForeground(new java.awt.Color(255, 102, 0));
        lblbirthday.setText("Birthday:");
        lblbirthday.setPreferredSize(new java.awt.Dimension(46, 17));

        txtbirthday.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txtbirthday.setForeground(new java.awt.Color(255, 255, 255));
        txtbirthday.setDateFormatString("dd/MM/yyyy");
        txtbirthday.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnbirthdayLayout = new javax.swing.GroupLayout(pnbirthday);
        pnbirthday.setLayout(pnbirthdayLayout);
        pnbirthdayLayout.setHorizontalGroup(
            pnbirthdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnbirthdayLayout.createSequentialGroup()
                .addComponent(lblbirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(txtbirthday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnbirthdayLayout.setVerticalGroup(
            pnbirthdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnbirthdayLayout.createSequentialGroup()
                .addComponent(lblbirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtbirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pngender.setBackground(new java.awt.Color(51, 51, 51));
        pngender.setPreferredSize(new java.awt.Dimension(75, 46));

        lblgender.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblgender.setForeground(new java.awt.Color(255, 102, 0));
        lblgender.setText("Gender:");
        lblgender.setPreferredSize(new java.awt.Dimension(46, 17));

        rabmale.setBackground(new java.awt.Color(51, 51, 51));
        rabgender.add(rabmale);
        rabmale.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rabmale.setForeground(new java.awt.Color(255, 102, 0));
        rabmale.setSelected(true);
        rabmale.setText("Male");
        rabmale.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        rabfemale.setBackground(new java.awt.Color(51, 51, 51));
        rabgender.add(rabfemale);
        rabfemale.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rabfemale.setForeground(new java.awt.Color(255, 102, 0));
        rabfemale.setText("Female");
        rabfemale.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        javax.swing.GroupLayout pngenderLayout = new javax.swing.GroupLayout(pngender);
        pngender.setLayout(pngenderLayout);
        pngenderLayout.setHorizontalGroup(
            pngenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pngenderLayout.createSequentialGroup()
                .addGroup(pngenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblgender, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pngenderLayout.createSequentialGroup()
                        .addComponent(rabmale, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(rabfemale, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pngenderLayout.setVerticalGroup(
            pngenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pngenderLayout.createSequentialGroup()
                .addComponent(lblgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(pngenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rabfemale)
                    .addComponent(rabmale)))
        );

        pnupdatedu.setBackground(new java.awt.Color(51, 51, 51));

        lblupdatedu.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblupdatedu.setForeground(new java.awt.Color(255, 102, 0));
        lblupdatedu.setText("Updated user:");

        txtupdatedu.setEditable(false);
        txtupdatedu.setBackground(new java.awt.Color(51, 51, 51));
        txtupdatedu.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtupdatedu.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnupdateduLayout = new javax.swing.GroupLayout(pnupdatedu);
        pnupdatedu.setLayout(pnupdateduLayout);
        pnupdateduLayout.setHorizontalGroup(
            pnupdateduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnupdateduLayout.createSequentialGroup()
                .addComponent(lblupdatedu, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(txtupdatedu)
        );
        pnupdateduLayout.setVerticalGroup(
            pnupdateduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnupdateduLayout.createSequentialGroup()
                .addComponent(lblupdatedu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtupdatedu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pncreatedu.setBackground(new java.awt.Color(51, 51, 51));

        lblupdateduser1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblupdateduser1.setForeground(new java.awt.Color(255, 102, 0));
        lblupdateduser1.setText("Created user:");

        txtcreatedu.setEditable(false);
        txtcreatedu.setBackground(new java.awt.Color(51, 51, 51));
        txtcreatedu.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtcreatedu.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pncreateduLayout = new javax.swing.GroupLayout(pncreatedu);
        pncreatedu.setLayout(pncreateduLayout);
        pncreateduLayout.setHorizontalGroup(
            pncreateduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pncreateduLayout.createSequentialGroup()
                .addComponent(lblupdateduser1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(txtcreatedu)
        );
        pncreateduLayout.setVerticalGroup(
            pncreateduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pncreateduLayout.createSequentialGroup()
                .addComponent(lblupdateduser1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcreatedu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnupdatedd.setBackground(new java.awt.Color(51, 51, 51));

        lblupdatedd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblupdatedd.setForeground(new java.awt.Color(255, 102, 0));
        lblupdatedd.setText("Updated date:");

        txtupdatedd.setEditable(false);
        txtupdatedd.setBackground(new java.awt.Color(51, 51, 51));
        txtupdatedd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtupdatedd.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnupdateddLayout = new javax.swing.GroupLayout(pnupdatedd);
        pnupdatedd.setLayout(pnupdateddLayout);
        pnupdateddLayout.setHorizontalGroup(
            pnupdateddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnupdateddLayout.createSequentialGroup()
                .addComponent(lblupdatedd, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(txtupdatedd)
        );
        pnupdateddLayout.setVerticalGroup(
            pnupdateddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnupdateddLayout.createSequentialGroup()
                .addComponent(lblupdatedd, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtupdatedd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pncreatedd.setBackground(new java.awt.Color(51, 51, 51));

        lblcreatedd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblcreatedd.setForeground(new java.awt.Color(255, 102, 0));
        lblcreatedd.setText("Created date:");

        txtcreatedd.setEditable(false);
        txtcreatedd.setBackground(new java.awt.Color(51, 51, 51));
        txtcreatedd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtcreatedd.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pncreateddLayout = new javax.swing.GroupLayout(pncreatedd);
        pncreatedd.setLayout(pncreateddLayout);
        pncreateddLayout.setHorizontalGroup(
            pncreateddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pncreateddLayout.createSequentialGroup()
                .addComponent(lblcreatedd, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
            .addComponent(txtcreatedd)
        );
        pncreateddLayout.setVerticalGroup(
            pncreateddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pncreateddLayout.createSequentialGroup()
                .addComponent(lblcreatedd, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcreatedd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnleftLayout = new javax.swing.GroupLayout(pnleft);
        pnleft.setLayout(pnleftLayout);
        pnleftLayout.setHorizontalGroup(
            pnleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnleftLayout.createSequentialGroup()
                .addGroup(pnleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnphone, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addGroup(pnleftLayout.createSequentialGroup()
                        .addComponent(pnid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(123, 123, 123))
                    .addComponent(pnbirthday, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(pnstatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(pncreatedu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pnleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnleftLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnimage, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnleftLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pngender, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(pnleftLayout.createSequentialGroup()
                .addGroup(pnleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnleftLayout.createSequentialGroup()
                        .addComponent(pncreatedd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnupdatedd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnupdatedu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnleftLayout.setVerticalGroup(
            pnleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnleftLayout.createSequentialGroup()
                .addGroup(pnleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnleftLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnbirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(pnstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnimage, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
                .addGroup(pnleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnleftLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(pngender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnleftLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pncreatedu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnleftLayout.createSequentialGroup()
                        .addComponent(pnupdatedu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnupdatedd, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pncreatedd, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addComponent(pnaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnright.setBackground(new java.awt.Color(51, 51, 51));

        pntbl.setBackground(new java.awt.Color(51, 51, 51));

        tblreader.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblreader.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblreader);
        if (tblreader.getColumnModel().getColumnCount() > 0) {
            tblreader.getColumnModel().getColumn(0).setMinWidth(40);
            tblreader.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblreader.getColumnModel().getColumn(0).setMaxWidth(40);
            tblreader.getColumnModel().getColumn(2).setMinWidth(100);
            tblreader.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblreader.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        javax.swing.GroupLayout pntblLayout = new javax.swing.GroupLayout(pntbl);
        pntbl.setLayout(pntblLayout);
        pntblLayout.setHorizontalGroup(
            pntblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pntblLayout.setVerticalGroup(
            pntblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
        );

        pnbutton.setBackground(new java.awt.Color(51, 51, 51));

        pnsearchid.setBackground(new java.awt.Color(51, 51, 51));

        lblsearchid.setBackground(new java.awt.Color(51, 51, 51));
        lblsearchid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblsearchid.setForeground(new java.awt.Color(255, 102, 0));
        lblsearchid.setText("ID: ");

        txtsearchid.setBackground(new java.awt.Color(51, 51, 51));
        txtsearchid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtsearchid.setForeground(new java.awt.Color(255, 255, 255));
        txtsearchid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txtsearchid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchidKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pnsearchidLayout = new javax.swing.GroupLayout(pnsearchid);
        pnsearchid.setLayout(pnsearchidLayout);
        pnsearchidLayout.setHorizontalGroup(
            pnsearchidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtsearchid)
            .addGroup(pnsearchidLayout.createSequentialGroup()
                .addComponent(lblsearchid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnsearchidLayout.setVerticalGroup(
            pnsearchidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnsearchidLayout.createSequentialGroup()
                .addComponent(lblsearchid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsearchid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnsearchname.setBackground(new java.awt.Color(51, 51, 51));

        lblsearchname.setBackground(new java.awt.Color(51, 51, 51));
        lblsearchname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblsearchname.setForeground(new java.awt.Color(255, 102, 0));
        lblsearchname.setText("Name:");

        txtsearchname.setBackground(new java.awt.Color(51, 51, 51));
        txtsearchname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtsearchname.setForeground(new java.awt.Color(255, 255, 255));
        txtsearchname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txtsearchname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchnameKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pnsearchnameLayout = new javax.swing.GroupLayout(pnsearchname);
        pnsearchname.setLayout(pnsearchnameLayout);
        pnsearchnameLayout.setHorizontalGroup(
            pnsearchnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtsearchname)
            .addGroup(pnsearchnameLayout.createSequentialGroup()
                .addComponent(lblsearchname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnsearchnameLayout.setVerticalGroup(
            pnsearchnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnsearchnameLayout.createSequentialGroup()
                .addComponent(lblsearchname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsearchname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnadd.setBackground(new java.awt.Color(51, 51, 51));
        btnadd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 102, 0));
        btnadd.setText("Add");
        btnadd.setBorder(null);
        btnadd.setPreferredSize(new java.awt.Dimension(85, 25));
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnsave.setBackground(new java.awt.Color(51, 51, 51));
        btnsave.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnsave.setForeground(new java.awt.Color(255, 102, 0));
        btnsave.setText("Save");
        btnsave.setBorder(null);
        btnsave.setPreferredSize(new java.awt.Dimension(85, 25));
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btndel.setBackground(new java.awt.Color(51, 51, 51));
        btndel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btndel.setForeground(new java.awt.Color(255, 102, 0));
        btndel.setText("Del");
        btndel.setBorder(null);
        btndel.setPreferredSize(new java.awt.Dimension(85, 25));
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });

        btnclear.setBackground(new java.awt.Color(51, 51, 51));
        btnclear.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 102, 0));
        btnclear.setText("Clear");
        btnclear.setBorder(null);
        btnclear.setPreferredSize(new java.awt.Dimension(85, 25));
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnbuttonLayout = new javax.swing.GroupLayout(pnbutton);
        pnbutton.setLayout(pnbuttonLayout);
        pnbuttonLayout.setHorizontalGroup(
            pnbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnsearchid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnsearchname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnbuttonLayout.createSequentialGroup()
                .addGroup(pnbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnbuttonLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnbuttonLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btndel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(pnbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnclear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        pnbuttonLayout.setVerticalGroup(
            pnbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnbuttonLayout.createSequentialGroup()
                .addComponent(pnsearchid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(pnsearchname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(pnbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnrightLayout = new javax.swing.GroupLayout(pnright);
        pnright.setLayout(pnrightLayout);
        pnrightLayout.setHorizontalGroup(
            pnrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pntbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnrightLayout.setVerticalGroup(
            pnrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnrightLayout.createSequentialGroup()
                .addComponent(pntbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnreaderLayout = new javax.swing.GroupLayout(pnreader);
        pnreader.setLayout(pnreaderLayout);
        pnreaderLayout.setHorizontalGroup(
            pnreaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnreaderLayout.createSequentialGroup()
                .addComponent(pnleft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnright, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnreaderLayout.setVerticalGroup(
            pnreaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnleft, javax.swing.GroupLayout.PREFERRED_SIZE, 551, Short.MAX_VALUE)
            .addComponent(pnright, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnreader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnreader, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimageActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser f = new JFileChooser("C:");
            f.setDialogTitle("Open file");
            f.showOpenDialog(null);
            File img = f.getSelectedFile();

            fileName = img.getName();
            imgpath = img.getAbsolutePath();
            setPicture(lblimage, imgpath);

            System.out.println(fileName);
            System.out.println(imgpath);
        } catch (Exception e) {
            System.out.println("You didn't pick an image yet");
        }
    }//GEN-LAST:event_btnimageActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        txtid.setText("");
        txtname.setText("");
        txtphone.setText("");
        txtbirthday.setDate(null);
        txtstatus.setText("");
        txtaddress.setText("");
        lblimage.setIcon(null);
        txtcreatedu.setText("");
        txtcreatedd.setText("");
        txtupdatedd.setText("");
        txtupdatedu.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        Readerdao rdao = new Readerdao();
        long millis = System.currentTimeMillis();
        Date date = new java.sql.Date(millis);
        if (txtid.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "What id men");
        } else {
            try {
                File f = new File("C:\\Users\\Uygi\\Documents\\NetBeansProjects\\JavaProjectAT\\src\\img\\reader\\" + fileName);
                imgpath = f.getAbsolutePath();
                ImageIO.write(image, "jpg", f);

                int g;
                if (rabmale.isSelected()) {
                    g = 1;
                } else {
                    g = 0;
                }
                java.sql.Date birth = convertJavaDateToSqlDate(txtbirthday.getDate());
                if (rdao.addNewReader(Integer.parseInt(txtid.getText()), imgpath, txtname.getText(), txtphone.getText(), birth, g, Integer.parseInt(txtstatus.getText()), txtaddress.getText(), date, s.getId(), date, s.getId())) {
                    JOptionPane.showMessageDialog(null, "Added " + txtid.getText() + " " + txtname.getText());
                    lstr = rdao.getAllReader();
                    DefaultTableModel dtm = (DefaultTableModel) tblreader.getModel();
                    dtm.setRowCount(0);
                    for (Reader r : lstr) {
                        Vector vt = new Vector();
                        vt.add(r.getId());
                        vt.add(r.getName());
                        vt.add(r.getPhone());

                        dtm.addRow(vt);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Add false");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Image");
            }
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        long millis = System.currentTimeMillis();
        Date date = new java.sql.Date(millis);
        Readerdao rdao = new Readerdao();
        try {
            File f = new File("C:\\Users\\Uygi\\Documents\\NetBeansProjects\\JavaProjectAT\\src\\img\\reader\\" + fileName);
            imgpath = f.getAbsolutePath();
            ImageIO.write(image, "jpg", f);

            int g;
            if (rabmale.isSelected()) {
                g = 1;
            } else {
                g = 0;
            }
            java.sql.Date birth = convertJavaDateToSqlDate(txtbirthday.getDate());

            if (rdao.updateReader(Integer.parseInt(txtid.getText()), imgpath, txtname.getText(), txtphone.getText(), birth, g, Integer.parseInt(txtstatus.getText()), txtaddress.getText(), Date.valueOf(txtcreatedd.getText()), ss, date, s.getId())) {
                JOptionPane.showMessageDialog(null, "Saved " + txtid.getText() + " " + txtname.getText());
                lstr = rdao.getAllReader();
                DefaultTableModel dtm = (DefaultTableModel) tblreader.getModel();
                dtm.setRowCount(0);
                for (Reader r : lstr) {
                    Vector vt = new Vector();
                    vt.add(r.getId());
                    vt.add(r.getName());
                    vt.add(r.getPhone());

                    dtm.addRow(vt);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Save false");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Image");
            System.out.println(e);
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        // TODO add your handling code here:
        File f = new File(imgpath);
        Readerdao rdao = new Readerdao();
        if (txtid.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pick a name and i'll make it dissapear");
        } else {
            if (rdao.delReader(Integer.parseInt(txtid.getText()))) {
                JOptionPane.showMessageDialog(null, "Deleted " + txtid.getText() + " " + txtname.getText());
                f.delete();
                lstr = rdao.getAllReader();
                DefaultTableModel dtm = (DefaultTableModel) tblreader.getModel();
                dtm.setRowCount(0);
                for (Reader r : lstr) {
                    Vector vt = new Vector();
                    vt.add(r.getId());
                    vt.add(r.getName());
                    vt.add(r.getPhone());

                    dtm.addRow(vt);
                }
                txtid.setText("");
                txtname.setText("");
                txtphone.setText("");
                txtstatus.setText("");
                txtaddress.setText("");
                txtbirthday.setDate(null);
                lblimage.setIcon(null);
            } else {
                JOptionPane.showMessageDialog(null, "Delete false");
            }
        }
    }//GEN-LAST:event_btndelActionPerformed

    private void txtsearchidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchidKeyPressed
        // TODO add your handling code here:
        Readerdao rdao = new Readerdao();
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            if (txtsearchid.getText().equals("")) {
                lstr = rdao.getAllReader();
                DefaultTableModel dtm = (DefaultTableModel) tblreader.getModel();
                dtm.setRowCount(0);
                for (Reader r : lstr) {
                    Vector vt = new Vector();
                    vt.add(r.getId());
                    vt.add(r.getName());
                    vt.add(r.getPhone());

                    dtm.addRow(vt);
                }
            } else {
                lstr = rdao.getReaderById(Integer.parseInt(txtsearchid.getText()));
                DefaultTableModel dtm = (DefaultTableModel) tblreader.getModel();
                dtm.setRowCount(0);
                for (Reader r : lstr) {
                    Vector vt = new Vector();
                    vt.add(r.getId());
                    vt.add(r.getName());
                    vt.add(r.getPhone());

                    dtm.addRow(vt);
                }
            }
        }
    }//GEN-LAST:event_txtsearchidKeyPressed

    private void txtsearchnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchnameKeyPressed
        // TODO add your handling code here:
        Readerdao rdao = new Readerdao();
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            if (txtsearchname.getText().equals("")) {
                lstr = rdao.getAllReader();
                DefaultTableModel dtm = (DefaultTableModel) tblreader.getModel();
                dtm.setRowCount(0);
                for (Reader r : lstr) {
                    Vector vt = new Vector();
                    vt.add(r.getId());
                    vt.add(r.getName());
                    vt.add(r.getPhone());

                    dtm.addRow(vt);
                }
            } else {
                lstr = rdao.getReaderByName(txtsearchname.getText());
                DefaultTableModel dtm = (DefaultTableModel) tblreader.getModel();
                dtm.setRowCount(0);
                for (Reader r : lstr) {
                    Vector vt = new Vector();
                    vt.add(r.getId());
                    vt.add(r.getName());
                    vt.add(r.getPhone());

                    dtm.addRow(vt);
                }
            }
        }
    }//GEN-LAST:event_txtsearchnameKeyPressed

    private ArrayList<Reader> lstr = null;
    private DateFormat dateformat = new SimpleDateFormat("dd/MM/yyyy");
    private BufferedImage image = null;
    private String imgpath, fileName, imgs;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnimage;
    private javax.swing.JButton btnsave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lblbirthday;
    private javax.swing.JLabel lblcreatedd;
    private javax.swing.JLabel lblcreateduser;
    private javax.swing.JLabel lblcreateduser1;
    private javax.swing.JLabel lblcreateduser2;
    private javax.swing.JLabel lblcreateduser3;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblidentity;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblphone;
    private javax.swing.JLabel lblsearchid;
    private javax.swing.JLabel lblsearchname;
    private javax.swing.JLabel lblupdatedd;
    private javax.swing.JLabel lblupdatedu;
    private javax.swing.JLabel lblupdateduser1;
    private javax.swing.JPanel pnaddress;
    private javax.swing.JPanel pnbirthday;
    private javax.swing.JPanel pnbutton;
    private javax.swing.JPanel pncreatedd;
    private javax.swing.JPanel pncreatedu;
    private javax.swing.JPanel pncreateduser;
    private javax.swing.JPanel pncreateduser1;
    private javax.swing.JPanel pncreateduser2;
    private javax.swing.JPanel pncreateduser3;
    private javax.swing.JPanel pngender;
    private javax.swing.JPanel pnid;
    private javax.swing.JPanel pnimage;
    private javax.swing.JPanel pnleft;
    private javax.swing.JPanel pnname;
    private javax.swing.JPanel pnphone;
    private javax.swing.JPanel pnreader;
    private javax.swing.JPanel pnright;
    private javax.swing.JPanel pnsearchid;
    private javax.swing.JPanel pnsearchname;
    private javax.swing.JPanel pnstatus;
    private javax.swing.JPanel pntbl;
    private javax.swing.JPanel pnupdatedd;
    private javax.swing.JPanel pnupdatedu;
    private javax.swing.JRadioButton rabfemale;
    private javax.swing.ButtonGroup rabgender;
    private javax.swing.JRadioButton rabmale;
    private javax.swing.JTable tblreader;
    private javax.swing.JTextArea txtaddress;
    private com.toedter.calendar.JDateChooser txtbirthday;
    private javax.swing.JTextField txtcreatedd;
    private javax.swing.JTextField txtcreatedu;
    private javax.swing.JTextField txtcreateduser;
    private javax.swing.JTextField txtcreateduser1;
    private javax.swing.JTextField txtcreateduser2;
    private javax.swing.JTextField txtcreateduser3;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtsearchid;
    private javax.swing.JTextField txtsearchname;
    private javax.swing.JTextField txtstatus;
    private javax.swing.JTextField txtupdatedd;
    private javax.swing.JTextField txtupdatedu;
    // End of variables declaration//GEN-END:variables
}
