/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import model.Staff;
import dao.Staffdao;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Uygi
 */
public class pnstaff extends javax.swing.JPanel {

    /**
     * Creates new form pnstaff
     */
    public pnstaff() {
        initComponents();
        showAllStaff();
        pickAStaff();
    }

    public void showAllStaff() {
        Staffdao sdao = new Staffdao();
        lsts = sdao.getAllStaff();
        DefaultTableModel dtm = (DefaultTableModel) tblstaff.getModel();
        dtm.setRowCount(0);
        for (Staff s : lsts) {
            Vector vt = new Vector();
            vt.add(s.getId());
            vt.add(s.getName());
            vt.add(s.getPhone());
            vt.add(s.getUser());

            dtm.addRow(vt);
        }
    }

    public void pickAStaff() {
        tblstaff.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int rowSelected = tblstaff.getSelectedRow();
                int row = (int) tblstaff.getValueAt(rowSelected, 0);

                Staffdao sdao = new Staffdao();
                Staff s = new Staff();
                s = sdao.getAStaffById(row);
                txtid.setText(Integer.toString((int) s.getId()));

                setPicture(lblimage, s.getAvatar());
                imgpath = s.getAvatar();
                imgs = s.getAvatar();

                txtname.setText(s.getName());
                txtuser.setText(s.getUser());
                txtpass.setText(s.getPass());
                txtphone.setText(s.getPhone());
                txtbirthday.setDate(s.getBirthday());
                txtstartd.setDate(s.getStartd());
                txtendd.setDate(s.getEndd());
                txtaddress.setText(s.getAddress());
                if (s.getGender() == 1) {
                    rabmale.setSelected(true);
                    rabfemale.setSelected(false);
                } else {
                    rabmale.setSelected(false);
                    rabfemale.setSelected(true);
                }
                if (s.getStatus() == 0) {
                    cbxstatuss.setSelected(false);
                } else {
                    cbxstatuss.setSelected(true);
                }

            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
    }

    public void setPicture(JLabel label, String filename) {
        try {
            image = ImageIO.read(new File(filename));
            ImageIcon icon = new ImageIcon(image.getScaledInstance(label.getWidth(), label.getHeight(), BufferedImage.SCALE_SMOOTH));
            label.setIcon(icon);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Something wrong with image");
            try {
                image = ImageIO.read(new File("C:\\Users\\Uygi\\Documents\\NetBeansProjects\\JavaProjectAT\\src\\img\\h.jpg"));
                ImageIcon icon = new ImageIcon(image.getScaledInstance(label.getWidth(), label.getHeight(), BufferedImage.SCALE_SMOOTH));
                lblimage.setIcon(icon);
            } catch (IOException exx) {
                System.out.println(exx);
            }
        }
    }

    public java.sql.Date convertJavaDateToSqlDate(java.util.Date date) {
        return new java.sql.Date(date.getTime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btggender = new javax.swing.ButtonGroup();
        pnstaff = new javax.swing.JPanel();
        pnleft = new javax.swing.JPanel();
        pnimage = new javax.swing.JPanel();
        lblimage = new javax.swing.JLabel();
        btnimage = new javax.swing.JButton();
        pnid = new javax.swing.JPanel();
        lblid = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        pnname = new javax.swing.JPanel();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        pnuser = new javax.swing.JPanel();
        lbluser = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        pnpass = new javax.swing.JPanel();
        lblpass = new javax.swing.JLabel();
        txtpass = new javax.swing.JTextField();
        pnphone = new javax.swing.JPanel();
        lblphone = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        pngender = new javax.swing.JPanel();
        lblgender = new javax.swing.JLabel();
        rabmale = new javax.swing.JRadioButton();
        rabfemale = new javax.swing.JRadioButton();
        pnbirthday = new javax.swing.JPanel();
        lblbirthday = new javax.swing.JLabel();
        txtbirthday = new com.toedter.calendar.JDateChooser();
        pnstartd = new javax.swing.JPanel();
        lblstartd = new javax.swing.JLabel();
        txtstartd = new com.toedter.calendar.JDateChooser();
        pnendd = new javax.swing.JPanel();
        lblendd = new javax.swing.JLabel();
        txtendd = new com.toedter.calendar.JDateChooser();
        pnaddress = new javax.swing.JPanel();
        lbladdress = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        pnstatus = new javax.swing.JPanel();
        lblstatus = new javax.swing.JLabel();
        cbxstatuss = new javax.swing.JCheckBox();
        pnright = new javax.swing.JPanel();
        pntbl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblstaff = new javax.swing.JTable();
        pnbutton = new javax.swing.JPanel();
        btnadd = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        pnsearchid = new javax.swing.JPanel();
        lblsearchid = new javax.swing.JLabel();
        txtsearchid = new javax.swing.JTextField();
        pnsearchname = new javax.swing.JPanel();
        lblsearchname = new javax.swing.JLabel();
        txtsearchname = new javax.swing.JTextField();

        pnstaff.setBackground(new java.awt.Color(51, 51, 51));
        pnstaff.setPreferredSize(new java.awt.Dimension(767, 544));

        pnleft.setBackground(new java.awt.Color(51, 51, 51));

        pnimage.setBackground(new java.awt.Color(51, 51, 51));
        pnimage.setPreferredSize(new java.awt.Dimension(250, 250));

        lblimage.setPreferredSize(new java.awt.Dimension(250, 250));

        btnimage.setBackground(new java.awt.Color(51, 51, 51));
        btnimage.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnimage.setForeground(new java.awt.Color(255, 102, 0));
        btnimage.setText("Pick Image");
        btnimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnimageLayout = new javax.swing.GroupLayout(pnimage);
        pnimage.setLayout(pnimageLayout);
        pnimageLayout.setHorizontalGroup(
            pnimageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnimageLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnimage)
                .addContainerGap(95, Short.MAX_VALUE))
            .addComponent(lblimage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnimageLayout.setVerticalGroup(
            pnimageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnimageLayout.createSequentialGroup()
                .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnimage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnid.setBackground(new java.awt.Color(51, 51, 51));

        lblid.setBackground(new java.awt.Color(51, 51, 51));
        lblid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblid.setForeground(new java.awt.Color(255, 102, 0));
        lblid.setText("ID: ");

        txtid.setBackground(new java.awt.Color(51, 51, 51));
        txtid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtid.setForeground(new java.awt.Color(255, 255, 255));
        txtid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        javax.swing.GroupLayout pnidLayout = new javax.swing.GroupLayout(pnid);
        pnid.setLayout(pnidLayout);
        pnidLayout.setHorizontalGroup(
            pnidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtid)
            .addGroup(pnidLayout.createSequentialGroup()
                .addComponent(lblid, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        pnidLayout.setVerticalGroup(
            pnidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnidLayout.createSequentialGroup()
                .addComponent(lblid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnname.setBackground(new java.awt.Color(51, 51, 51));
        pnname.setPreferredSize(new java.awt.Dimension(73, 44));

        lblname.setBackground(new java.awt.Color(51, 51, 51));
        lblname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 102, 0));
        lblname.setText("Name:");

        txtname.setBackground(new java.awt.Color(51, 51, 51));
        txtname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtname.setForeground(new java.awt.Color(255, 255, 255));
        txtname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        javax.swing.GroupLayout pnnameLayout = new javax.swing.GroupLayout(pnname);
        pnname.setLayout(pnnameLayout);
        pnnameLayout.setHorizontalGroup(
            pnnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtname)
            .addGroup(pnnameLayout.createSequentialGroup()
                .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnnameLayout.setVerticalGroup(
            pnnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnnameLayout.createSequentialGroup()
                .addComponent(lblname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnuser.setBackground(new java.awt.Color(51, 51, 51));
        pnuser.setPreferredSize(new java.awt.Dimension(73, 44));

        lbluser.setBackground(new java.awt.Color(51, 51, 51));
        lbluser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbluser.setForeground(new java.awt.Color(255, 102, 0));
        lbluser.setText("User name:");

        txtuser.setBackground(new java.awt.Color(51, 51, 51));
        txtuser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtuser.setForeground(new java.awt.Color(255, 255, 255));
        txtuser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        javax.swing.GroupLayout pnuserLayout = new javax.swing.GroupLayout(pnuser);
        pnuser.setLayout(pnuserLayout);
        pnuserLayout.setHorizontalGroup(
            pnuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnuserLayout.createSequentialGroup()
                .addComponent(lbluser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(txtuser)
        );
        pnuserLayout.setVerticalGroup(
            pnuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnuserLayout.createSequentialGroup()
                .addComponent(lbluser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnpass.setBackground(new java.awt.Color(51, 51, 51));
        pnpass.setPreferredSize(new java.awt.Dimension(73, 44));

        lblpass.setBackground(new java.awt.Color(51, 51, 51));
        lblpass.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblpass.setForeground(new java.awt.Color(255, 102, 0));
        lblpass.setText("Pass:");

        txtpass.setBackground(new java.awt.Color(51, 51, 51));
        txtpass.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtpass.setForeground(new java.awt.Color(255, 255, 255));
        txtpass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        javax.swing.GroupLayout pnpassLayout = new javax.swing.GroupLayout(pnpass);
        pnpass.setLayout(pnpassLayout);
        pnpassLayout.setHorizontalGroup(
            pnpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnpassLayout.createSequentialGroup()
                .addComponent(lblpass, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(txtpass)
        );
        pnpassLayout.setVerticalGroup(
            pnpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnpassLayout.createSequentialGroup()
                .addComponent(lblpass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnphone.setBackground(new java.awt.Color(51, 51, 51));
        pnphone.setPreferredSize(new java.awt.Dimension(73, 44));

        lblphone.setBackground(new java.awt.Color(51, 51, 51));
        lblphone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblphone.setForeground(new java.awt.Color(255, 102, 0));
        lblphone.setText("Phone:");

        txtphone.setBackground(new java.awt.Color(51, 51, 51));
        txtphone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtphone.setForeground(new java.awt.Color(255, 255, 255));
        txtphone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        javax.swing.GroupLayout pnphoneLayout = new javax.swing.GroupLayout(pnphone);
        pnphone.setLayout(pnphoneLayout);
        pnphoneLayout.setHorizontalGroup(
            pnphoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnphoneLayout.createSequentialGroup()
                .addComponent(lblphone, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(txtphone)
        );
        pnphoneLayout.setVerticalGroup(
            pnphoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnphoneLayout.createSequentialGroup()
                .addComponent(lblphone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pngender.setBackground(new java.awt.Color(51, 51, 51));
        pngender.setPreferredSize(new java.awt.Dimension(268, 46));

        lblgender.setBackground(new java.awt.Color(51, 51, 51));
        lblgender.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblgender.setForeground(new java.awt.Color(255, 102, 0));
        lblgender.setText("Gender: ");

        rabmale.setBackground(new java.awt.Color(51, 51, 51));
        btggender.add(rabmale);
        rabmale.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rabmale.setForeground(new java.awt.Color(255, 102, 0));
        rabmale.setText("Male");

        rabfemale.setBackground(new java.awt.Color(51, 51, 51));
        btggender.add(rabfemale);
        rabfemale.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rabfemale.setForeground(new java.awt.Color(255, 102, 0));
        rabfemale.setText("Female");

        javax.swing.GroupLayout pngenderLayout = new javax.swing.GroupLayout(pngender);
        pngender.setLayout(pngenderLayout);
        pngenderLayout.setHorizontalGroup(
            pngenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pngenderLayout.createSequentialGroup()
                .addGroup(pngenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblgender, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pngenderLayout.createSequentialGroup()
                        .addComponent(rabmale)
                        .addGap(44, 44, 44)
                        .addComponent(rabfemale)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        pngenderLayout.setVerticalGroup(
            pngenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pngenderLayout.createSequentialGroup()
                .addComponent(lblgender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pngenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rabmale)
                    .addComponent(rabfemale)))
        );

        pnbirthday.setBackground(new java.awt.Color(51, 51, 51));
        pnbirthday.setPreferredSize(new java.awt.Dimension(73, 44));

        lblbirthday.setBackground(new java.awt.Color(51, 51, 51));
        lblbirthday.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblbirthday.setForeground(new java.awt.Color(255, 102, 0));
        lblbirthday.setText("Birthday: ");

        txtbirthday.setBackground(new java.awt.Color(255, 255, 255));
        txtbirthday.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txtbirthday.setForeground(new java.awt.Color(255, 255, 255));
        txtbirthday.setDateFormatString("dd/MM/yyyy");
        txtbirthday.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnbirthdayLayout = new javax.swing.GroupLayout(pnbirthday);
        pnbirthday.setLayout(pnbirthdayLayout);
        pnbirthdayLayout.setHorizontalGroup(
            pnbirthdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnbirthdayLayout.createSequentialGroup()
                .addComponent(lblbirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(txtbirthday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnbirthdayLayout.setVerticalGroup(
            pnbirthdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnbirthdayLayout.createSequentialGroup()
                .addComponent(lblbirthday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtbirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnstartd.setBackground(new java.awt.Color(51, 51, 51));
        pnstartd.setPreferredSize(new java.awt.Dimension(73, 44));

        lblstartd.setBackground(new java.awt.Color(51, 51, 51));
        lblstartd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblstartd.setForeground(new java.awt.Color(255, 102, 0));
        lblstartd.setText("Start date:");

        txtstartd.setBackground(new java.awt.Color(255, 255, 255));
        txtstartd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txtstartd.setForeground(new java.awt.Color(255, 255, 255));
        txtstartd.setDateFormatString("dd/MM/yyyy");
        txtstartd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnstartdLayout = new javax.swing.GroupLayout(pnstartd);
        pnstartd.setLayout(pnstartdLayout);
        pnstartdLayout.setHorizontalGroup(
            pnstartdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnstartdLayout.createSequentialGroup()
                .addComponent(lblstartd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(txtstartd, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        pnstartdLayout.setVerticalGroup(
            pnstartdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnstartdLayout.createSequentialGroup()
                .addComponent(lblstartd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtstartd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnendd.setBackground(new java.awt.Color(51, 51, 51));
        pnendd.setPreferredSize(new java.awt.Dimension(73, 44));

        lblendd.setBackground(new java.awt.Color(51, 51, 51));
        lblendd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblendd.setForeground(new java.awt.Color(255, 102, 0));
        lblendd.setText("End date:");

        txtendd.setBackground(new java.awt.Color(255, 255, 255));
        txtendd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txtendd.setForeground(new java.awt.Color(255, 255, 255));
        txtendd.setDateFormatString("dd/MM/yyyy");
        txtendd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnenddLayout = new javax.swing.GroupLayout(pnendd);
        pnendd.setLayout(pnenddLayout);
        pnenddLayout.setHorizontalGroup(
            pnenddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnenddLayout.createSequentialGroup()
                .addComponent(lblendd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(txtendd, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        pnenddLayout.setVerticalGroup(
            pnenddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnenddLayout.createSequentialGroup()
                .addComponent(lblendd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtendd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnaddress.setBackground(new java.awt.Color(51, 51, 51));

        lbladdress.setBackground(new java.awt.Color(51, 51, 51));
        lbladdress.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbladdress.setForeground(new java.awt.Color(255, 102, 0));
        lbladdress.setText("Address:");

        txtaddress.setBackground(new java.awt.Color(51, 51, 51));
        txtaddress.setColumns(20);
        txtaddress.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtaddress.setForeground(new java.awt.Color(255, 255, 255));
        txtaddress.setRows(5);
        txtaddress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jScrollPane2.setViewportView(txtaddress);

        javax.swing.GroupLayout pnaddressLayout = new javax.swing.GroupLayout(pnaddress);
        pnaddress.setLayout(pnaddressLayout);
        pnaddressLayout.setHorizontalGroup(
            pnaddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnaddressLayout.createSequentialGroup()
                .addComponent(lbladdress, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        pnaddressLayout.setVerticalGroup(
            pnaddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnaddressLayout.createSequentialGroup()
                .addComponent(lbladdress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2))
        );

        pnstatus.setBackground(new java.awt.Color(51, 51, 51));
        pnstatus.setPreferredSize(new java.awt.Dimension(268, 46));

        lblstatus.setBackground(new java.awt.Color(51, 51, 51));
        lblstatus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblstatus.setForeground(new java.awt.Color(255, 102, 0));
        lblstatus.setText("Status:");

        cbxstatuss.setBackground(new java.awt.Color(51, 51, 51));
        cbxstatuss.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbxstatuss.setForeground(new java.awt.Color(255, 102, 0));
        cbxstatuss.setText("Online");

        javax.swing.GroupLayout pnstatusLayout = new javax.swing.GroupLayout(pnstatus);
        pnstatus.setLayout(pnstatusLayout);
        pnstatusLayout.setHorizontalGroup(
            pnstatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnstatusLayout.createSequentialGroup()
                .addComponent(lblstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(cbxstatuss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnstatusLayout.setVerticalGroup(
            pnstatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnstatusLayout.createSequentialGroup()
                .addComponent(lblstatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbxstatuss))
        );

        javax.swing.GroupLayout pnleftLayout = new javax.swing.GroupLayout(pnleft);
        pnleft.setLayout(pnleftLayout);
        pnleftLayout.setHorizontalGroup(
            pnleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnleftLayout.createSequentialGroup()
                .addGroup(pnleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnleftLayout.createSequentialGroup()
                        .addGroup(pnleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnname, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(pnuser, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(pnpass, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(pnphone, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(pnbirthday, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addGroup(pnleftLayout.createSequentialGroup()
                                .addComponent(pnid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(141, 141, 141)))
                        .addGap(10, 10, 10)
                        .addGroup(pnleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnimage, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnleftLayout.createSequentialGroup()
                                .addComponent(pngender, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))))
                    .addComponent(pnaddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnleftLayout.createSequentialGroup()
                        .addComponent(pnstartd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(pnendd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(pnstatus, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnleftLayout.setVerticalGroup(
            pnleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnleftLayout.createSequentialGroup()
                .addGroup(pnleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnleftLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(pnname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(pnpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnleftLayout.createSequentialGroup()
                        .addComponent(pnid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(pnuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnimage, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pngender, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnbirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnstartd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnendd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnaddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnright.setBackground(new java.awt.Color(51, 51, 51));
        pnright.setPreferredSize(new java.awt.Dimension(238, 496));

        pntbl.setBackground(new java.awt.Color(51, 51, 51));

        tblstaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Phone", "User Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblstaff);
        if (tblstaff.getColumnModel().getColumnCount() > 0) {
            tblstaff.getColumnModel().getColumn(0).setMinWidth(40);
            tblstaff.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblstaff.getColumnModel().getColumn(0).setMaxWidth(40);
            tblstaff.getColumnModel().getColumn(2).setMinWidth(100);
            tblstaff.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblstaff.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        javax.swing.GroupLayout pntblLayout = new javax.swing.GroupLayout(pntbl);
        pntbl.setLayout(pntblLayout);
        pntblLayout.setHorizontalGroup(
            pntblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pntblLayout.setVerticalGroup(
            pntblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pntblLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnbutton.setBackground(new java.awt.Color(51, 51, 51));

        btnadd.setBackground(new java.awt.Color(51, 51, 51));
        btnadd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 102, 0));
        btnadd.setText("Add");
        btnadd.setBorder(null);
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnsave.setBackground(new java.awt.Color(51, 51, 51));
        btnsave.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnsave.setForeground(new java.awt.Color(255, 102, 0));
        btnsave.setText("Save");
        btnsave.setBorder(null);
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btndel.setBackground(new java.awt.Color(51, 51, 51));
        btndel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btndel.setForeground(new java.awt.Color(255, 102, 0));
        btndel.setText("Del");
        btndel.setBorder(null);
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });

        btnclear.setBackground(new java.awt.Color(51, 51, 51));
        btnclear.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 102, 0));
        btnclear.setText("Clear");
        btnclear.setBorder(null);
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        pnsearchid.setBackground(new java.awt.Color(51, 51, 51));
        pnsearchid.setPreferredSize(new java.awt.Dimension(0, 44));

        lblsearchid.setBackground(new java.awt.Color(51, 51, 51));
        lblsearchid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblsearchid.setForeground(new java.awt.Color(255, 102, 0));
        lblsearchid.setText("ID:");

        txtsearchid.setBackground(new java.awt.Color(51, 51, 51));
        txtsearchid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtsearchid.setForeground(new java.awt.Color(255, 255, 255));
        txtsearchid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txtsearchid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchidKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pnsearchidLayout = new javax.swing.GroupLayout(pnsearchid);
        pnsearchid.setLayout(pnsearchidLayout);
        pnsearchidLayout.setHorizontalGroup(
            pnsearchidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtsearchid)
            .addGroup(pnsearchidLayout.createSequentialGroup()
                .addComponent(lblsearchid, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnsearchidLayout.setVerticalGroup(
            pnsearchidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnsearchidLayout.createSequentialGroup()
                .addComponent(lblsearchid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtsearchid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnsearchname.setBackground(new java.awt.Color(51, 51, 51));
        pnsearchname.setPreferredSize(new java.awt.Dimension(0, 44));

        lblsearchname.setBackground(new java.awt.Color(51, 51, 51));
        lblsearchname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblsearchname.setForeground(new java.awt.Color(255, 102, 0));
        lblsearchname.setText("Name:");

        txtsearchname.setBackground(new java.awt.Color(51, 51, 51));
        txtsearchname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtsearchname.setForeground(new java.awt.Color(255, 255, 255));
        txtsearchname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txtsearchname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchnameKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pnsearchnameLayout = new javax.swing.GroupLayout(pnsearchname);
        pnsearchname.setLayout(pnsearchnameLayout);
        pnsearchnameLayout.setHorizontalGroup(
            pnsearchnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtsearchname)
            .addGroup(pnsearchnameLayout.createSequentialGroup()
                .addComponent(lblsearchname, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnsearchnameLayout.setVerticalGroup(
            pnsearchnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnsearchnameLayout.createSequentialGroup()
                .addComponent(lblsearchname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtsearchname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnbuttonLayout = new javax.swing.GroupLayout(pnbutton);
        pnbutton.setLayout(pnbuttonLayout);
        pnbuttonLayout.setHorizontalGroup(
            pnbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnbuttonLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btndel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
            .addComponent(pnsearchid, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
            .addComponent(pnsearchname, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        );
        pnbuttonLayout.setVerticalGroup(
            pnbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnbuttonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnsearchid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnsearchname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(pnbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnbuttonLayout.createSequentialGroup()
                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(pnbuttonLayout.createSequentialGroup()
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btndel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
        );

        javax.swing.GroupLayout pnrightLayout = new javax.swing.GroupLayout(pnright);
        pnright.setLayout(pnrightLayout);
        pnrightLayout.setHorizontalGroup(
            pnrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pntbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnrightLayout.setVerticalGroup(
            pnrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnrightLayout.createSequentialGroup()
                .addComponent(pntbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnstaffLayout = new javax.swing.GroupLayout(pnstaff);
        pnstaff.setLayout(pnstaffLayout);
        pnstaffLayout.setHorizontalGroup(
            pnstaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnstaffLayout.createSequentialGroup()
                .addComponent(pnleft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnright, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnstaffLayout.setVerticalGroup(
            pnstaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnleft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnright, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnstaff, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnstaff, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        txtid.setText("");
        txtname.setText("");
        txtuser.setText("");
        txtpass.setText("");
        txtphone.setText("");
        txtbirthday.setDate(null);
        txtstartd.setDate(null);
        txtendd.setDate(null);
        lblimage.setIcon(null);
        txtaddress.setText("");
        cbxstatuss.setSelected(false);
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        if (txtid.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "What id men");
        } else {
            try {
                File f = new File("C:\\Users\\Uygi\\Documents\\NetBeansProjects\\JavaProjectAT\\src\\img\\staff\\" + fileName);
                imgpath = f.getAbsolutePath();
                ImageIO.write(image, "jpg", f);

                int g;
                if (rabmale.isSelected()) {
                    g = 1;
                } else {
                    g = 0;
                }
                int status;
                if (cbxstatuss.isSelected()) {
                    status = 1;
                } else {
                    status = 0;
                }
                java.sql.Date birth = convertJavaDateToSqlDate(txtbirthday.getDate());
                java.sql.Date start = convertJavaDateToSqlDate(txtstartd.getDate());
                java.sql.Date end = convertJavaDateToSqlDate(txtendd.getDate());
                Staffdao sdao = new Staffdao();
                if (sdao.addNewStaff(Integer.parseInt(txtid.getText()), imgpath, txtuser.getText(),
                        txtpass.getText(), txtname.getText(), txtphone.getText(), birth, g,
                        txtaddress.getText(), status, start, end)) {
                    JOptionPane.showMessageDialog(null, "Added " + txtid.getText() + " " + txtname.getText());
                    lsts = sdao.getAllStaff();
                    DefaultTableModel dtm = (DefaultTableModel) tblstaff.getModel();
                    dtm.setRowCount(0);
                    for (Staff s : lsts) {
                        Vector vt = new Vector();
                        vt.add(s.getId());
                        vt.add(s.getName());
                        vt.add(s.getPhone());
                        vt.add(s.getUser());

                        dtm.addRow(vt);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Add false");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Image");
            }
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        if (txtid.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pick a name asshole!");
        } else {
            try {
                File f = new File("C:\\Users\\Uygi\\Documents\\NetBeansProjects\\JavaProjectAT\\src\\img\\staff\\" + fileName);
                imgpath = f.getAbsolutePath();
                ImageIO.write(image, "jpg", f);
                File fi = new File(imgs);
                fi.delete();
                int g;
                if (rabmale.isSelected()) {
                    g = 1;
                } else {
                    g = 0;
                }
                int status;
                if (cbxstatuss.isSelected()) {
                    status = 1;
                } else {
                    status = 0;
                }
                java.sql.Date birth = convertJavaDateToSqlDate(txtbirthday.getDate());
                java.sql.Date start = convertJavaDateToSqlDate(txtstartd.getDate());
                java.sql.Date end = convertJavaDateToSqlDate(txtendd.getDate());
                Staffdao sdao = new Staffdao();
                if (sdao.updateStaff(Integer.parseInt(txtid.getText()), txtuser.getText(),
                        txtpass.getText(), imgpath, txtname.getText(), txtphone.getText(), birth, g,
                        txtaddress.getText(), status, start, end)) {
                    JOptionPane.showMessageDialog(null, "Saved " + txtid.getText() + ": " + txtname.getText());
                    lsts = sdao.getAllStaff();
                    DefaultTableModel dtm = (DefaultTableModel) tblstaff.getModel();
                    dtm.setRowCount(0);
                    for (Staff s : lsts) {
                        Vector vt = new Vector();
                        vt.add(s.getId());
                        vt.add(s.getName());
                        vt.add(s.getPhone());
                        vt.add(s.getUser());

                        dtm.addRow(vt);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Save false");
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Image");
            }
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        // TODO add your handling code here:
        File f = new File(imgpath);
        Staffdao sdao = new Staffdao();
        if (txtid.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pick a name and i'll make it dissapear");
        } else {
            if (sdao.delStaff(Integer.parseInt(txtid.getText()))) {
                JOptionPane.showMessageDialog(null, "Deleted " + txtid.getText() + ": " + txtname.getText());
                f.delete();
                lsts = sdao.getAllStaff();
                DefaultTableModel dtm = (DefaultTableModel) tblstaff.getModel();
                dtm.setRowCount(0);
                for (Staff s : lsts) {
                    Vector vt = new Vector();
                    vt.add(s.getId());
                    vt.add(s.getName());
                    vt.add(s.getPhone());
                    vt.add(s.getUser());

                    dtm.addRow(vt);
                }
                txtid.setText("");
                txtname.setText("");
                txtuser.setText("");
                txtpass.setText("");
                txtphone.setText("");
                txtbirthday.setDate(null);
                txtstartd.setDate(null);
                txtendd.setDate(null);
                lblimage.setIcon(null);
                txtaddress.setText("");
                cbxstatuss.setSelected(false);
            } else {
                JOptionPane.showMessageDialog(null, "Delete false");
            }
        }
    }//GEN-LAST:event_btndelActionPerformed

    private void btnimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimageActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser f = new JFileChooser("C:");
            f.setDialogTitle("Open file");
            f.showOpenDialog(null);
            File img = f.getSelectedFile();

            fileName = img.getName();
            imgpath = img.getAbsolutePath();
            setPicture(lblimage, imgpath);

            System.out.println(fileName);
            System.out.println(imgpath);
        } catch (Exception e) {
            System.out.println("You didn't pick an image yet");
        }
    }//GEN-LAST:event_btnimageActionPerformed

    private void txtsearchidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchidKeyPressed
        // TODO add your handling code here:
        Staffdao sdao = new Staffdao();
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            if (txtsearchid.getText().equals("")) {
                lsts = sdao.getAllStaff();
                DefaultTableModel dtm = (DefaultTableModel) tblstaff.getModel();
                dtm.setRowCount(0);
                for (Staff s : lsts) {
                    Vector vt = new Vector();
                    vt.add(s.getId());
                    vt.add(s.getName());
                    vt.add(s.getPhone());
                    vt.add(s.getUser());

                    dtm.addRow(vt);
                }
            } else {
                lsts = sdao.getAllStaffById(Integer.parseInt(txtsearchid.getText()));
                DefaultTableModel dtm = (DefaultTableModel) tblstaff.getModel();
                dtm.setRowCount(0);
                for (Staff s : lsts) {
                    Vector vt = new Vector();
                    vt.add(s.getId());
                    vt.add(s.getName());
                    vt.add(s.getPhone());
                    vt.add(s.getUser());

                    dtm.addRow(vt);
                }
            }
        }
    }//GEN-LAST:event_txtsearchidKeyPressed

    private void txtsearchnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchnameKeyPressed
        // TODO add your handling code here:
        Staffdao sdao = new Staffdao();
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            if (txtsearchname.getText().equals("")) {
                lsts = sdao.getAllStaff();
                DefaultTableModel dtm = (DefaultTableModel) tblstaff.getModel();
                dtm.setRowCount(0);
                for (Staff s : lsts) {
                    Vector vt = new Vector();
                    vt.add(s.getId());
                    vt.add(s.getName());
                    vt.add(s.getPhone());
                    vt.add(s.getUser());

                    dtm.addRow(vt);
                }
            } else {
                lsts = sdao.getAllStaffByName(txtsearchname.getText());
                DefaultTableModel dtm = (DefaultTableModel) tblstaff.getModel();
                dtm.setRowCount(0);
                for (Staff s : lsts) {
                    Vector vt = new Vector();
                    vt.add(s.getId());
                    vt.add(s.getName());
                    vt.add(s.getPhone());
                    vt.add(s.getUser());

                    dtm.addRow(vt);
                }
            }
        }
    }//GEN-LAST:event_txtsearchnameKeyPressed

    private ArrayList<Staff> lsts = null;
    private DateFormat dateformat = new SimpleDateFormat("dd/MM/yyyy");
    private BufferedImage image = null;
    private String imgpath, fileName, imgs;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btggender;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnimage;
    private javax.swing.JButton btnsave;
    private javax.swing.JCheckBox cbxstatuss;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lblbirthday;
    private javax.swing.JLabel lblendd;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lblphone;
    private javax.swing.JLabel lblsearchid;
    private javax.swing.JLabel lblsearchname;
    private javax.swing.JLabel lblstartd;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JLabel lbluser;
    private javax.swing.JPanel pnaddress;
    private javax.swing.JPanel pnbirthday;
    private javax.swing.JPanel pnbutton;
    private javax.swing.JPanel pnendd;
    private javax.swing.JPanel pngender;
    private javax.swing.JPanel pnid;
    private javax.swing.JPanel pnimage;
    private javax.swing.JPanel pnleft;
    private javax.swing.JPanel pnname;
    private javax.swing.JPanel pnpass;
    private javax.swing.JPanel pnphone;
    private javax.swing.JPanel pnright;
    private javax.swing.JPanel pnsearchid;
    private javax.swing.JPanel pnsearchname;
    private javax.swing.JPanel pnstaff;
    private javax.swing.JPanel pnstartd;
    private javax.swing.JPanel pnstatus;
    private javax.swing.JPanel pntbl;
    private javax.swing.JPanel pnuser;
    private javax.swing.JRadioButton rabfemale;
    private javax.swing.JRadioButton rabmale;
    private javax.swing.JTable tblstaff;
    private javax.swing.JTextArea txtaddress;
    private com.toedter.calendar.JDateChooser txtbirthday;
    private com.toedter.calendar.JDateChooser txtendd;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtsearchid;
    private javax.swing.JTextField txtsearchname;
    private com.toedter.calendar.JDateChooser txtstartd;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
